### PR TITLE
Upgrade to latest compound-web package

### PR DESCRIPTION
**Pull request by MidhunSureshR**
[compound-web 6.0.0 release](https://github.com/element-hq/compound-web/releases/tag/v6.0.0) introduced some breaking changes related to Tooltips. 

- Brought back `<TooltipProvider>` component to all the root components. It was removed in https://github.com/matrix-org/matrix-react-sdk/pull/12416/.
- Adds a custom render function that wraps the component under test with `<TooltipProvider>`. All tests must now import from `jest-matrix-react` instead of `@testing-library/react`. An eslint rule is added to enforce the same.
- When providing `label` to Tooltip, it acts as an accessible label for the enclosed element. Also when used in this manner, `role=tooltip` is not added. Since this was the primary way tooltips were found and asserted, a lot of tests broke. They are fixed by searching via text or by using `description` prop instead of `label prop.
- Fixes https://github.com/element-hq/element-web/issues/28087 by pinning `wrap-ansi` and `wrap-ansi-cjs` to a specific version. Yarn is otherwise unable to understand that these are both the same package. This would result in `yarn install` failing perpetually. 
- `<ToggleMenuItem>` no longer has an `onChange`, updated [src/components/views/right_panel/RoomSummaryCard.tsx](https://github.com/element-hq/matrix-react-sdk/pull/84/files#diff-cccc430ecf9f7ea5343c40e96d20d57625544d24cbd81c9aebb4f4b31896fc61).
- [Playwright accessibility tests will ignore elements with id starting with `floating-ui-`](https://github.com/element-hq/matrix-react-sdk/pull/84/files#diff-fa202c5ca8bf17b4afd7827765221390319d109bd3cb83cb7aa1c1d6d2a4c389). These are the divs outside `.MatrixChat` where the tooltips are rendered. The reason for fail: `Ensure all page content is contained by landmarks`. Since the tooltips are only shown on user interaction, this is probably fine.
- Increased timeout for flaky tests - [here](https://github.com/element-hq/matrix-react-sdk/pull/84/files#diff-bb27e520cf2f92439112fc98cdfd014e47043ee1b03654b04a60553512cab21aR255) and [here](https://github.com/element-hq/matrix-react-sdk/pull/84/files#diff-3eac9db9ac940d0798995d358eee216ba2aaca29bf893a53f2dc8139544d8c58R212).

### CODE REVIEW

**Comment by MidhunSureshR** [comment]
Needs https://github.com/element-hq/compound-web/pull/248 for fixing the type error.

**Review by florianduros — APPROVED** [review]
Fine I gess :))

**Comment by t3chguy** [comment]
Maybe this could be broken down to 2, decoupling the `jest-matrix-react` stuff from the compound upgrade as having snapshots update whilst tests are also changing increases the risk

**Review by richvdh — APPROVED** [review]
LGTM from the crypto POV. Will leave it to the web team to decide if they are happy with combining the `jest-matrix-react` stuff with the compound upgrade

**Pull request merged**
