### PR TITLE
Add support for rendering media captions

### PR DESCRIPTION
**Pull request by tulir**
Depends on https://github.com/matrix-org/matrix-js-sdk/pull/4403

Preview:

image

<details>
<summary>When hovering over image</summary>

image

</details>

### CODE REVIEW

**Review by dbkr — COMMENTED** [review]
Code look good - this will probably need a look from design though. Could you add a screenshot to make it easier?

**Comment by tulir** [comment]
Added screenshot

**Comment by dbkr** [comment]
and what a screenshot it is. Requested design review, with promise of cats.

**Review by amshakal — APPROVED** [review]
LGTM. 
th-4091376590

**Review by dbkr — APPROVED** [review]

**Comment by tulir** [comment]
Not sure why that test only failed in the merge queue 🤔 I guess I'll add another mock there

**Comment by frebib** [comment]
This works great with modern layout, but is quite broken with bubble layout. Some captions are not visible with image bubbles 🤔

**Comment by tulir** [comment]
🙀

**Pull request merged**
