### PR TITLE
Fix outstanding UX issues with replies/mentions/keyword notifs

### LINKED ISSUE #8821: Notifications triggered by keywords don't decorate messages - Highlight keywords in a pill
Should follow the same convention as @mention decoration— currently with the notifying word in a pill and the entire message highlighted red.

### PR DESCRIPTION
**Pull request by taffyko**
## Checklist

-   [X] Tests written for new code (and old code if feasible).
-   [X] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [X] Linter and other CI checks pass.
-   [X] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/matrix-react-sdk)

## Purpose
- Closes the long-outstanding issue https://github.com/element-hq/element-meta/issues/744,
- @robintown's [original PR](https://github.com/matrix-org/matrix-react-sdk/pull/9199) for this was blocked due to a [small edge-case](https://github.com/matrix-org/matrix-react-sdk/pull/9199#issuecomment-1497987388) in visual clarity:
When following a link to a message with keyword notifications, there would no longer be any visual indication that the message triggered a notification.
  - This PR implements her [recommended solution](https://github.com/element-hq/element-meta/issues/744#issuecomment-1440712735), clarifying notification keywords by displaying them in pills.
  - By implementing keyword pills, this closes https://github.com/element-hq/element-web/issues/8821 as well.

For the "Modern" layout, a bright stripe has been added to the left edge of the highlighted-message background to improve visibility for mentions/notifications, in the spirit of https://github.com/element-hq/element-meta/issues/1476.

| Before  | After |
| ------------- | ------------- |
| Pasted image 20240922225036 | Pasted image 20240922225435 |
| Pasted image 20240922225030 | Pasted image 20240922225105 |

### CODE REVIEW

**Comment by dbkr** [comment]
Flagged for design review. Where did the design come from here (eg. the stripe colour)?

**Comment by taffyko** [comment]
@dbkr The stripe takes cues from the layout we already use for selected messages (after following a link to a message)
image
with the color based on the contrast that Discord's similar highlighted-message style uses.
image

I had seen a few ticket comments from the community expressing the sentiment that (especially in light mode) the visibility of the "highlighted-message" background can be poor, and a style similar to Discord's would be appreciated — so I followed that sentiment in my design.
Apart from that, there was no formal design process for the stripe — but as a contributor, I'd love to learn how to get involved there!

I can drop it from the PR if it presents an issue.

**Comment by dbkr** [comment]
Okay, thanks. The colour probably should come from one of the colours in the compound colour scheme already, if there's an appropriate one, but this is all for a designer to look at.

**Comment by t3chguy** [comment]
We have made the decision to merge matrix-react-sdk into https://github.com/element-hq/element-web - if you are still interested in this contribution please move it to that repository. Closing so it does not remain as a zombie

**Pull request closed without merging**
